"""PDF export: real ReportLab output, read back with pypdf."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from pypdf import PdfReader

from app.models.agent_outputs import ReportSection
from app.models.domain import Citation, SourceType, VerificationStatus
from app.services.report_pdf import build_report_pdf, inline_markup, to_pdf_text
from app.services.report_render import StoredReport
from tests.fakes import report

WHEN = datetime(2026, 10, 2, 18, 30, tzinfo=UTC)


def citation(cid: str, status: VerificationStatus, kind: SourceType = SourceType.WEB) -> Citation:
    reference = f"https://example.org/{cid.lower()}?a=1&b=2" if kind is SourceType.WEB else "notes.pdf, p. 3"
    return Citation(id=cid, title=f"Source {cid} <title>", reference=reference, source_type=kind,
                    verification_status=status, excerpt="...")


def stored(**changes) -> StoredReport:
    body = report("Evidence [W1] [W2] [K1]")
    body.detailed_analysis = [
        ReportSection(heading="Costs", content="Para one with **bold** [W1].\n\n- point A [W2]\n- point B\n\n"
                                                "### Sub-topic\nDetails & more <tags> [K1]."),
    ]
    data = {
        "report": body,
        "citations": [
            citation("W1", VerificationStatus.CORROBORATED),
            citation("W2", VerificationStatus.UNVERIFIED),
            citation("K1", VerificationStatus.SINGLE_SOURCE, SourceType.KNOWLEDGE_BASE),
        ],
        "quality_notes": ["2 of 3 cited sources are not corroborated by a second source."],
    } | changes
    return StoredReport(**data)


def read(path: Path) -> tuple[PdfReader, str]:
    reader = PdfReader(path)
    text = "\n".join(page.extract_text() for page in reader.pages)
    return reader, " ".join(text.split())


def test_pdf_contains_all_sections_references_and_metadata(tmp_path: Path) -> None:
    path = build_report_pdf(stored(), tmp_path / "r.pdf", query="How have solar costs changed?", generated_at=WHEN)
    assert path.read_bytes().startswith(b"%PDF-")
    reader, text = read(path)
    for heading in ("Solar Energy Cost Trends", "Executive Summary", "Introduction", "Research Questions",
                    "Methodology", "Key Findings", "Detailed Analysis", "Limitations", "Conclusion",
                    "References", "Quality Notes", "Sub-topic"):
        assert heading in text, heading
    assert "How have solar costs changed?" in text and "02 October 2026" in text
    assert "Details & more <tags>" in text  # escaped, not interpreted as markup
    assert reader.metadata.title == "Solar Energy Cost Trends" and reader.metadata.author == "ResearchPilot"


def test_references_are_numbered_and_verification_is_clearly_marked(tmp_path: Path) -> None:
    _, text = read(build_report_pdf(stored(), tmp_path / "r.pdf", query="q", generated_at=WHEN))
    assert "1. [W1] Source W1 <title>. Web source: https://example.org/w1?a=1&b=2" in text
    assert "Verification: Corroborated by multiple sources" in text
    assert "2. [W2]" in text and "Verification: UNVERIFIED - could not be verified" in text
    assert "3. [K1] Source K1 <title>. Knowledge base: notes.pdf, p. 3" in text
    assert "Single source - not independently corroborated" in text


def test_citations_link_to_references_and_urls_are_clickable(tmp_path: Path) -> None:
    reader, _ = read(build_report_pdf(stored(), tmp_path / "r.pdf", query="q", generated_at=WHEN))
    links = [annot.get_object() for page in reader.pages for annot in page.get("/Annots", [])]
    uris = {str(a["/A"]["/URI"]) for a in links if "/A" in a and "/URI" in a["/A"]}
    assert "https://example.org/w1?a=1&b=2" in uris
    internal = [a for a in links if "/Dest" in a or ("/A" in a and a["/A"].get("/S") == "/GoTo")]
    assert internal  # [W1] etc. jump to the reference list


def test_report_without_citations_says_so(tmp_path: Path) -> None:
    _, text = read(build_report_pdf(stored(citations=[], quality_notes=[]), tmp_path / "r.pdf",
                                    query="q", generated_at=WHEN))
    assert "No sources were cited." in text and "Quality Notes" not in text


def test_long_reports_paginate_with_footer(tmp_path: Path) -> None:
    long = stored()
    long.report.detailed_analysis = [
        ReportSection(heading=f"Section {i}", content=" ".join(["Long analysis sentence [W1]."] * 60))
        for i in range(8)
    ]
    reader, text = read(build_report_pdf(long, tmp_path / "r.pdf", query="q", generated_at=WHEN))
    assert len(reader.pages) >= 3
    assert "Page 1" in text and f"Page {len(reader.pages)}" in text
    assert "Generated by ResearchPilot" in text


def test_build_is_atomic_and_overwrites(tmp_path: Path) -> None:
    path = tmp_path / "nested" / "r.pdf"
    build_report_pdf(stored(), path, query="q", generated_at=WHEN)
    build_report_pdf(stored(), path, query="q2", generated_at=WHEN)
    assert path.exists() and not list(path.parent.glob("*.tmp"))


def test_unicode_is_made_safe_for_builtin_fonts() -> None:
    assert to_pdf_text("costs → down ≥ 40% — “quoted” café") == 'costs -> down >= 40% — “quoted” café'
    assert to_pdf_text("中文") == "??"
    assert to_pdf_text("ﬁnance") == "finance"  # ligature decomposed


def test_inline_markup_escapes_and_links_only_known_citations() -> None:
    markup = inline_markup("**Key** & <b>raw</b> [W1, W9] *note* `code`", {"W1"})
    assert "<b>Key</b> &amp; &lt;b&gt;raw&lt;/b&gt;" in markup
    assert '<a href="#ref-W1" color="#1a56db">W1</a>, W9]' in markup
    assert "<i>note</i>" in markup and '<font face="Courier">code</font>' in markup


def test_numbered_lists_and_kb_references_render_cleanly(tmp_path: Path) -> None:
    data = stored()
    data.citations[2] = Citation(id="K1", title="notes.md", reference="notes.md", source_type=SourceType.KNOWLEDGE_BASE,
                                 verification_status=VerificationStatus.SINGLE_SOURCE, excerpt="")
    _, text = read(build_report_pdf(data, tmp_path / "r.pdf", query="q", generated_at=WHEN))
    assert "1. How have solar costs changed?" in text  # numbered with a period
    assert "3. [K1] notes.md. Knowledge base Verification" in text  # no duplicated file name
